$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: model
command: >-
  python train.py
  --training_data ${{inputs.training_data}}
  --target_col Diabetic
inputs:
  training_data: 
    type: uri_folder 
    path: /subscriptions/860f94f9-3790-4e05-923f-12728796f2ec/resourceGroups/rg-dp100-labs/providers/Microsoft.MachineLearningServices/workspaces/mlw-dp100-labs/data/diabetes-prod-folder/versions/1
  reg_rate: 0.01
environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
compute: azureml:aml-cluster
experiment_name: diabetes-train-experiment
description: Training of an ML model to recognize the presence of diabetes in an individual