name: Linting and Testing for model training script

on:
    pull_request:

jobs:
    lint_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v3
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip |
                pip install -r requirements.txt |
                python3 -m pip install flake8 pytest
            - name: Lint with flake8
              run: |
                  flake8 ./src/model/
            - name: Test with pytest
              run: |
                  pytest ./src/model/
