name: Train a LR model in a development and production environment

on:
  push:
    branches: [ main ]

jobs:
    experiment:
        runs-on: ubuntu-latest
        env:
            ENVIRONMENT: development
        steps:
        - name: Check out repo
          uses: actions/checkout@main
        - name: Install az ml extension
          run: az extension add -n ml -y
        - name: Azure login
          uses: azure/login@v1
          with:
            creds: ${{secrets.AZURE_CREDENTIALS}}
        - name: Running diabetes training model phase
          run: az ml job create -g rg-dp100-labs -w mlw-dp100-labs -f ./src/dev_train.yml -n dev_train --stream
    production:
        runs-on: ubuntu-latest
        needs: experiment
        if: ${{ success() }}
        env:
            ENVIRONMENT: production
        steps:
        - name: Check out repo
          uses: actions/checkout@main
        - name: Install az ml extension
          run: az extension add -n ml -y
        - name: Azure login
          uses: azure/login@v1
          with:
            creds: ${{secrets.AZURE_CREDENTIALS}}
        - name: Running diabetes training model phase
          run: az ml job create -g rg-dp100-labs -w mlw-dp100-labs -f ./src/prod_train.yml -n prod_train --stream
