name: Pull-based trigger of a workflow

on:
  pull_request:

jobs:
  train:
      runs-on: ubuntu-latest
      steps:
      - name: Placeholder
        run: |
          echo "Will add code checks here in next challenge"
