name: Push-based trigger of a workflow

on:
  push:

jobs:
  train:
      runs-on: ubuntu-latest
      steps:
      - name: Placeholder
        run: |
          echo "Will add code checks here in next challenge"
